spring.application.name=iread-backend
spring.config.import=optional:classpath:application-local.properties

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB
app.file-storage.type=local
app.file-storage.local.upload-dir=uploads/images
app.file-storage.local.public-url=/uploads/images
