-- 운영 환경에서도 훈련 기준 데이터가 항상 동일하도록 JSON 기준 원본을 반영한다.
-- 기존 PK/FK는 유지하며 prompt의 알려지지 않은 속성은 JSON_MERGE_PATCH로 보존한다.

INSERT INTO curriculum_units (id, unit_name, sequence_no)
VALUES
    (1, '글자 따라 보기', 1),
    (2, '소리 듣고 고르기', 2),
    (3, '글자 만들기', 3),
    (4, '글자 자르기', 4),
    (5, '글자 대치', 5),
    (6, '글 해독', 6),
    (7, '문장 완성 및 이해', 7),
    (8, '유창하게 읽기', 8)
ON DUPLICATE KEY UPDATE
    unit_name = VALUES(unit_name),
    sequence_no = VALUES(sequence_no);

INSERT INTO training_templates (id, curriculum_unit_id, name, prompt, sequence_no)
VALUES
    (1, 1, '모음 따라 보기', '{"trainingType":"VOWEL_TRACE","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"기본 모음 또는 복합 모음의 형태와 획순을 익히는 데이터를 생성한다. vowelType은 BASIC 또는 COMPLEX만 사용하고 target에는 완성된 한글 모음 하나를 넣는다. soundText는 실제 소릿값이며 같은 target을 중복하지 않는다. traceAssetKey는 영문 소문자, 숫자, 밑줄만 사용한다.","outputTemplate":{"type":"VOWEL_TRACE","data":[{"vowelType":"<string>","target":"<string>","soundText":"<string>","traceAssetKey":"<string>"}]},"supportedFeatureCategories":["GRAPHEME"],"supportedScopes":["CHARACTER"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (2, 1, '자음 따라 보기', '{"trainingType":"CONSONANT_TRACE","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"기본 자음, 된소리 또는 거센소리의 형태와 획순을 익히는 데이터를 생성한다. consonantType은 BASIC, TENSE, ASPIRATED 중 하나만 사용한다. target은 한글 자음 하나이며 soundText에는 자음 이름이 아닌 실제 소릿값을 넣는다.","outputTemplate":{"type":"CONSONANT_TRACE","data":[{"consonantType":"<string>","target":"<string>","soundText":"<string>","traceAssetKey":"<string>"}]},"supportedFeatureCategories":["GRAPHEME"],"supportedScopes":["CHARACTER"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (3, 1, '음절 따라 보기', '{"trainingType":"SYLLABLE_TRACE","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"받침 없는 음절, 받침 있는 음절, 복합 모음 또는 된소리가 포함된 음절을 생성한다. syllableType은 WITHOUT_FINAL, WITH_FINAL, COMPLEX_VOWEL, TENSE_CONSONANT 중 하나이며 target의 실제 구조와 일치해야 한다.","outputTemplate":{"type":"SYLLABLE_TRACE","data":[{"syllableType":"<string>","target":"<string>","soundText":"<string>","traceAssetKey":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 3),
    (4, 2, '자음 소리 고르기', '{"trainingType":"CONSONANT_SOUND_CHOICE","requiredInputs":[],"additionalPrompt":"자음 소리를 듣고 알맞은 자음 카드를 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. audioText는 자음 이름이 아닌 실제 소릿값이고 choices에는 한글 자음만 넣는다. answerIndex를 실제 정답 위치와 일치시킨다.","outputTemplate":{"type":"CONSONANT_SOUND_CHOICE","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME"],"supportedScopes":["CHARACTER"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (5, 2, '모음 소리 고르기', '{"trainingType":"VOWEL_SOUND_CHOICE","requiredInputs":[],"additionalPrompt":"모음 소리를 듣고 알맞은 모음 카드를 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. audioText는 목표 모음의 실제 소릿값이고 choices에는 한글 모음만 넣는다. 형태나 소리가 비슷한 오답을 포함한다.","outputTemplate":{"type":"VOWEL_SOUND_CHOICE","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME"],"supportedScopes":["CHARACTER"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (6, 2, '자음·모음 구별하기', '{"trainingType":"CONSONANT_VOWEL_CLASSIFICATION","requiredInputs":[],"additionalPrompt":"한글 자모의 소리를 듣고 자음인지 모음인지 구별한다. choices는 반드시 CONSONANT과 VOWEL 두 값이며 정답은 목표 자모의 실제 분류와 일치해야 한다.","outputTemplate":{"type":"CONSONANT_VOWEL_CLASSIFICATION","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME"],"supportedScopes":["CHARACTER"],"promptVersion":"TRAINING_PROMPT_V2"}', 3),
    (7, 2, '음절의 첫소리 찾기', '{"trainingType":"SYLLABLE_INITIAL_CHOICE","requiredInputs":[],"additionalPrompt":"한글 음절 하나를 듣고 실제 초성을 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. choices에는 초성 자음만 넣고 오답은 정답과 형태나 소리가 비슷한 자음을 우선 사용한다.","outputTemplate":{"type":"SYLLABLE_INITIAL_CHOICE","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 4),
    (8, 2, '낱말의 첫소리 찾기', '{"trainingType":"WORD_INITIAL_CHOICE","requiredInputs":[],"additionalPrompt":"친숙한 실제 낱말을 듣고 첫 음절의 초성을 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. choices에는 초성 자음만 넣고 받침이나 의미가 아니라 첫소리만으로 판단할 수 있게 구성한다.","outputTemplate":{"type":"WORD_INITIAL_CHOICE","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","WORD"],"supportedScopes":["CHARACTER","WORD"],"promptVersion":"TRAINING_PROMPT_V2"}', 5),
    (9, 2, '같은 첫소리 낱말 찾기', '{"trainingType":"SAME_INITIAL_WORD_CHOICE","requiredInputs":[],"additionalPrompt":"targetType은 SYLLABLE 또는 WORD, choiceType은 WORD 또는 IMAGE_WORD만 사용한다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. targetAudioText와 정답 낱말의 초성이 같고 오답은 다른 초성으로 시작해야 한다. WORD의 imagePrompt는 빈 문자열이다.","outputTemplate":{"type":"SAME_INITIAL_WORD_CHOICE","data":[{"targetType":"<string>","targetAudioText":"<string>","choiceType":"<string>","choices":[{"text":"<string>","imagePrompt":"<string>"}],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","WORD"],"supportedScopes":["CHARACTER","SYLLABLE","WORD"],"promptVersion":"TRAINING_PROMPT_V2"}', 6),
    (10, 2, '받침 소리 고르기', '{"trainingType":"FINAL_CONSONANT_CHOICE","requiredInputs":[],"additionalPrompt":"받침이 있는 한글 음절 하나를 듣고 실제 종성 자음을 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. choices에는 종성 자음만 넣고 낮은 난이도에서는 표기와 발음이 달라지는 복잡한 음운 규칙을 피한다.","outputTemplate":{"type":"FINAL_CONSONANT_CHOICE","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 7),
    (11, 2, '낱말의 끝소리 고르기', '{"trainingType":"WORD_FINAL_SOUND_CHOICE","requiredInputs":[],"additionalPrompt":"친숙한 받침 포함 낱말을 듣고 마지막에 들리는 표준 발음의 끝소리를 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. 낮은 난이도에서는 음운 변동이 없는 낱말을 우선한다.","outputTemplate":{"type":"WORD_FINAL_SOUND_CHOICE","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","PHONOLOGY","WORD"],"supportedScopes":["CHARACTER","SYLLABLE","WORD"],"promptVersion":"TRAINING_PROMPT_V2"}', 8),
    (12, 2, '서로 다른 받침 음절 비교하기', '{"trainingType":"FINAL_CONSONANT_COMPARISON","requiredInputs":[],"additionalPrompt":"같은 초성과 중성을 가지면서 받침만 다른 음절 중 목표 음절을 고른다. choices는 정답 1개와 중복 없는 오답 2개를 포함해 정확히 3개로 생성한다. choices는 가능한 한 초성과 중성을 공유하고 종성만 다르게 구성하며 정답은 audioText와 정확히 일치한다.","outputTemplate":{"type":"FINAL_CONSONANT_COMPARISON","data":[{"audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 9),
    (13, 2, '비슷한 소리 고르기', '{"trainingType":"SIMILAR_SOUND_CHOICE","requiredInputs":[],"additionalPrompt":"soundGroup은 PLAIN_ASPIRATED, PLAIN_TENSE, ASPIRATED_TENSE, SIMILAR_PLACE 중 하나다. audioText에는 목표 자음 또는 간단한 음절을 넣고 choices는 해당 유사 소리 그룹으로 구성한다.","outputTemplate":{"type":"SIMILAR_SOUND_CHOICE","data":[{"soundGroup":"<string>","audioText":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 10),
    (14, 3, '음소 합쳐 음절 만들기', '{"trainingType":"PHONEME_BLEND","requiredInputs":["VOICE"],"additionalPrompt":"분리된 초성, 중성, 필요한 경우 종성을 순서대로 합쳐 한글 음절을 만든다. cards에는 정답 음소와 방해 카드를 넣고 answerOrder는 result를 만드는 cards 인덱스 순서다.","outputTemplate":{"type":"PHONEME_BLEND","data":[{"audioParts":["<string>"],"cards":["<string>"],"answerOrder":["<integer>"],"result":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (15, 3, '음절 합쳐 낱말 만들기', '{"trainingType":"SYLLABLE_BLEND","requiredInputs":["VOICE"],"additionalPrompt":"분리된 음절을 순서대로 합쳐 친숙한 실제 낱말을 만든다. cards에는 정답과 방해 음절을 넣고 answerOrder는 result를 만드는 cards 인덱스 순서다.","outputTemplate":{"type":"SYLLABLE_BLEND","data":[{"audioParts":["<string>"],"cards":["<string>"],"answerOrder":["<integer>"],"result":"<string>"}]},"supportedFeatureCategories":["SYLLABLE","WORD"],"supportedScopes":["SYLLABLE","WORD"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (16, 3, '기본 글자 만들기', '{"trainingType":"BASIC_SYLLABLE_BUILD","requiredInputs":["VOICE"],"additionalPrompt":"받침 없는 동일한 음절을 듣고 초성과 중성을 조합한다. initialChoices와 medialChoices에는 각각 올바른 자모만 넣고 정답 인덱스의 자모 결합은 result와 일치해야 한다.","outputTemplate":{"type":"BASIC_SYLLABLE_BUILD","data":[{"targetAudioText":"<string>","initialChoices":["<string>"],"medialChoices":["<string>"],"initialAnswerIndex":"<integer>","medialAnswerIndex":"<integer>","result":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 3),
    (17, 3, '받침 글자 만들기', '{"trainingType":"FINAL_SYLLABLE_BUILD","requiredInputs":["VOICE"],"additionalPrompt":"받침 있는 동일한 음절을 듣고 초성, 중성, 홑받침을 조합한다. 각 choices에는 올바른 종류의 자모만 넣고 세 정답 자모의 결합은 result와 일치해야 한다.","outputTemplate":{"type":"FINAL_SYLLABLE_BUILD","data":[{"targetAudioText":"<string>","initialChoices":["<string>"],"medialChoices":["<string>"],"finalChoices":["<string>"],"initialAnswerIndex":"<integer>","medialAnswerIndex":"<integer>","finalAnswerIndex":"<integer>","result":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 4),
    (18, 3, '겹받침 글자 만들기', '{"trainingType":"DOUBLE_FINAL_BUILD","requiredInputs":["VOICE"],"additionalPrompt":"겹받침이 포함된 음절 범위로 일관되게 생성한다. finalChoices에는 정답 겹받침과 혼동 가능한 홑받침 또는 다른 겹받침을 넣고 정답 자모 결합은 result의 목표 음절과 일치해야 한다.","outputTemplate":{"type":"DOUBLE_FINAL_BUILD","data":[{"targetAudioText":"<string>","initialChoices":["<string>"],"medialChoices":["<string>"],"finalChoices":["<string>"],"initialAnswerIndex":"<integer>","medialAnswerIndex":"<integer>","finalAnswerIndex":"<integer>","result":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 5),
    (19, 4, '받침 빼기', '{"trainingType":"FINAL_CONSONANT_DELETE","requiredInputs":["VOICE"],"additionalPrompt":"받침 있는 한글 음절 source에서 종성만 제거한다. removableUnits에는 방해 자음 없이 source를 분해한 초성, 중성, 종성을 순서대로 넣고 answerIndex는 종성 위치를 가리킨다. targetAudioText와 result는 종성을 제거한 음절로 같아야 한다.","outputTemplate":{"type":"FINAL_CONSONANT_DELETE","data":[{"source":"<string>","targetAudioText":"<string>","removableUnits":["<string>"],"answerIndex":"<integer>","result":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE"],"supportedScopes":["CHARACTER","SYLLABLE"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (20, 4, '음절 빼기', '{"trainingType":"SYLLABLE_DELETE","requiredInputs":["VOICE"],"additionalPrompt":"두 음절 이상의 source를 syllables 순서로 분해하고 deleteIndex의 한 음절을 제거해 result를 만든다. targetAudioText와 result는 같은 내용이어야 한다.","outputTemplate":{"type":"SYLLABLE_DELETE","data":[{"source":"<string>","targetAudioText":"<string>","syllables":["<string>"],"deleteIndex":"<integer>","result":"<string>"}]},"supportedFeatureCategories":["SYLLABLE","WORD"],"supportedScopes":["SYLLABLE","WORD"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (21, 5, '음절 바꾸기', '{"trainingType":"SYLLABLE_REPLACE","requiredInputs":["VOICE"],"additionalPrompt":"두 음절 이상의 source와 result는 정확히 한 음절만 달라야 한다. replaceIndex와 answerIndex의 선택지를 적용하면 result가 되며 가능한 한 친숙한 실제 낱말을 사용한다.","outputTemplate":{"type":"SYLLABLE_REPLACE","data":[{"source":"<string>","targetAudioText":"<string>","replaceIndex":"<integer>","choices":["<string>"],"answerIndex":"<integer>","result":"<string>"}]},"supportedFeatureCategories":["SYLLABLE","WORD"],"supportedScopes":["SYLLABLE","WORD"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (22, 6, '낱말 읽기', '{"trainingType":"WORD_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"readingOrder는 FREE 또는 SEQUENTIAL이다. words에는 친숙한 실제 낱말을 중복 없이 넣고 난이도에 따라 음절 수, 받침, 복합 모음과 된소리를 조절한다.","outputTemplate":{"type":"WORD_READING","data":[{"readingOrder":"<string>","words":["<string>"]}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD"],"supportedScopes":["CHARACTER","SYLLABLE","WORD","WORD_BOUNDARY"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (23, 6, '새 낱말 읽기', '{"trainingType":"NONWORD_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"실제 낱말과 발음 가능한 비단어를 생성한다. isNonword=true는 일반적으로 쓰이는 실제 낱말이 아니고 false는 실제 낱말이어야 하며 두 종류 요청 시 모두 포함한다.","outputTemplate":{"type":"NONWORD_READING","data":[{"words":[{"text":"<string>","isNonword":"<boolean>"}]}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD"],"supportedScopes":["CHARACTER","SYLLABLE","WORD","WORD_BOUNDARY"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (24, 6, '어려운 단어 먼저 읽기', '{"trainingType":"DIFFICULT_WORD_PREVIEW","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"문장에 동일한 표기로 포함된 어려운 낱말을 먼저 음절 단위로 연습한다. syllables 결합은 word와 같고 sentence는 초등학생이 이해할 수 있는 자연스러운 한 문장이다.","outputTemplate":{"type":"DIFFICULT_WORD_PREVIEW","data":[{"difficultWords":[{"word":"<string>","syllables":["<string>"]}],"sentence":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["CHARACTER","SYLLABLE","WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 3),
    (25, 6, '문장 읽기', '{"trainingType":"SENTENCE_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"처음부터 끝까지 순서대로 읽을 자연스러운 한 문장을 생성한다. tokens에는 강조할 어절을 순서대로 넣고 공백으로 결합해 문장부호를 복원하면 sentence와 일치해야 한다.","outputTemplate":{"type":"SENTENCE_READING","data":[{"sentence":"<string>","tokens":["<string>"]}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["CHARACTER","SYLLABLE","WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 4),
    (26, 6, '짧은 글 읽기', '{"trainingType":"SHORT_PASSAGE_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"정확한 해독을 위한 2~3문장의 짧은 글을 생성한다. 문장 흐름은 자연스럽고 서술 중심이며 복잡한 비유나 배경지식을 피한다.","outputTemplate":{"type":"SHORT_PASSAGE_READING","data":[{"sentences":["<string>"]}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["CHARACTER","SYLLABLE","WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 5),
    (27, 7, '문장 전체 조립', '{"trainingType":"SENTENCE_ASSEMBLY","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"섞인 낱말 또는 어절 cards를 answerOrder대로 배열하면 completedSentence가 되어야 한다. 초기 cards 순서는 정답 순서와 다르고 하나의 명확한 정답만 가능해야 한다.","outputTemplate":{"type":"SENTENCE_ASSEMBLY","data":[{"cards":["<string>"],"answerOrder":["<integer>"],"completedSentence":"<string>"}]},"supportedFeatureCategories":["WORD","SENTENCE"],"supportedScopes":["WORD","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (28, 7, '빈칸에 알맞은 단어 넣기', '{"trainingType":"FILL_IN_THE_BLANK","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"sentence에 {{blank}}를 정확히 한 번 넣는다. inputType은 CHOICE, TEXT, VOICE, HANDWRITING 중 하나다. 직접 입력은 choices 빈 배열과 answerIndex -1이며 정답을 넣으면 completedSentence와 일치한다.","outputTemplate":{"type":"FILL_IN_THE_BLANK","data":[{"sentence":"<string>","inputType":"<string>","choices":["<string>"],"answerIndex":"<integer>","acceptedAnswers":["<string>"],"completedSentence":"<string>"}]},"supportedFeatureCategories":["WORD","SENTENCE"],"supportedScopes":["WORD","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (29, 7, '그림과 문장 연결하기', '{"trainingType":"IMAGE_SENTENCE_MATCH","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"imagePrompt에는 인물, 행동, 장소와 물체가 명확한 장면을 넣는다. choices에는 그림을 정확히 설명하는 문장 하나와 핵심 요소가 다른 중복 없는 오답을 넣는다.","outputTemplate":{"type":"IMAGE_SENTENCE_MATCH","data":[{"imagePrompt":"<string>","choices":["<string>"],"answerIndex":"<integer>"}]},"supportedFeatureCategories":["WORD","SENTENCE"],"supportedScopes":["WORD","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 3),
    (30, 8, '문장 따라 읽기', '{"trainingType":"SENTENCE_REPEAT","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"모범 음성의 발음, 속도, 억양과 끊기를 따라 읽을 문장을 생성한다. emotion은 NEUTRAL, HAPPY, SAD, ANGRY, EXCITED, CALM 중 하나이며 내용과 자연스럽게 일치해야 한다.","outputTemplate":{"type":"SENTENCE_REPEAT","data":[{"sentence":"<string>","emotion":"<string>"}]},"supportedFeatureCategories":["PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 1),
    (31, 8, '단어 이어 읽기', '{"trainingType":"WORD_CHAIN_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"requiredOrder는 SEQUENTIAL만 사용한다. 이미 해독할 수 있는 실제 낱말을 한 문제 안에서 중복하지 않고 난이도에 따라 길이와 받침 구조를 조절한다.","outputTemplate":{"type":"WORD_CHAIN_READING","data":[{"words":["<string>"],"requiredOrder":"<string>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD"],"supportedScopes":["SYLLABLE","WORD","WORD_BOUNDARY"],"promptVersion":"TRAINING_PROMPT_V2"}', 2),
    (32, 8, '끊어 읽기', '{"trainingType":"PHRASE_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"자연스러운 문장을 의미 단위 2~4개의 phrases로 나눈다. 조사와 수식어를 잘못 분리하지 않고 phrases를 결합하면 sentence와 일치해야 한다.","outputTemplate":{"type":"PHRASE_READING","data":[{"sentence":"<string>","phrases":["<string>"]}]},"supportedFeatureCategories":["PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 3),
    (33, 8, '같은 문장 다시 읽기', '{"trainingType":"REPEATED_SENTENCE_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"정확도, 속도와 멈춤을 개선하도록 반복해도 자연스러운 문장을 생성한다. repeatCount는 2 이상의 정수이며 문장은 초등학생이 이해할 수 있어야 한다.","outputTemplate":{"type":"REPEATED_SENTENCE_READING","data":[{"sentence":"<string>","repeatCount":"<integer>"}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["SYLLABLE","WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 4),
    (34, 8, '짧은 이야기 읽기', '{"trainingType":"SHORT_STORY_READING","requiredInputs":["VOICE","GAZE"],"additionalPrompt":"자연스러운 속도와 감정으로 읽을 안전한 짧은 이야기를 생성한다. speaker는 NARRATOR 또는 CHARACTER이고 emotion은 NEUTRAL, HAPPY, SAD, ANGRY, SURPRISED, EXCITED, CALM 중 하나다.","outputTemplate":{"type":"SHORT_STORY_READING","data":[{"title":"<string>","sentences":[{"speaker":"<string>","text":"<string>","emotion":"<string>"}]}]},"supportedFeatureCategories":["GRAPHEME","SYLLABLE","PHONOLOGY","WORD","SENTENCE"],"supportedScopes":["SYLLABLE","WORD","WORD_BOUNDARY","SENTENCE"],"promptVersion":"TRAINING_PROMPT_V2"}', 5)
ON DUPLICATE KEY UPDATE
    curriculum_unit_id = VALUES(curriculum_unit_id),
    name = VALUES(name),
    prompt = JSON_MERGE_PATCH(prompt, VALUES(prompt)),
    sequence_no = VALUES(sequence_no);

-- 템플릿 15는 음절 합치기이며 읽기 속도 측정용 구형 분류가 아니다.
UPDATE training_templates
SET prompt = JSON_REMOVE(prompt, '$.questionType')
WHERE id = 15;
